
apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: pika


spec:
  replicas: 1
  serviceName: pika-svc
  selector:
    matchLabels:
      app: pika

  template:
    metadata:
      labels:
        app: pika
    spec: 
      containers:
        - name: pika
          ports:
            - containerPort: 3004
          image: blob421/local_friends-pika:latest
          command: ["python", "detect.py"]
          volumeMounts:
            - name: media-pvc
              mountPath: /usr/src/app/media/

      volumes:
        - name: media-pvc
          volumeClaimTemplates:
            claimName: mediaData
      