apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  replicas: 1
  serviceName: mongo-svc
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:latest
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_DATABASE
              value: local_friends 
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
    volumes:
      - name: mongo-storage
        persistentVolumeClaim:
          claimName: mongo-pvc
