import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Nav from './components/navbar_handler'
import { cookies } from 'next/headers';
//CSS//
import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.css";
import './styles/landing.css'
import './styles/login.css'
import './styles/registration.css'
import './styles/navbar.css'
import './styles/dashboard.css'
import './styles/home.css'

//////


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 const cookieStore = await cookies();
 const jwt = cookieStore.get('jwt');

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {jwt && <Nav />}
        {children}
      </body>
    </html>
  );
}
